Repository gardener/gardener-extension-auditing, pull requests merged in 2025-09, with the labels that each got.

#4 Add .gitkeep file to bin folder
  Makefile
  hack/tools/bin/.gitkeep
Labels: area/quality, kind/bug, size/XS, cla: yes, approved, lgtm

#3 Add support for gzip compression
  docs/api-reference/auditing.md
  go.mod
  go.sum
  imagevector/images.yaml
  pkg/apis/auditing/types.go
  pkg/apis/auditing/v1alpha1/types.go
  pkg/apis/auditing/v1alpha1/zz_generated.conversion.go
  pkg/apis/auditing/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/auditing/validation/validation.go
  pkg/apis/auditing/validation/validation_test.go
  pkg/apis/auditing/zz_generated.deepcopy.go
  pkg/component/auditlog-forwarder/deploy.go
  pkg/controller/audit/actuator.go
Labels: area/cost, kind/enhancement, size/L, cla: yes, approved, lgtm

#6 Switch auditlog-forwarder image repository to the virtual repository 'public'
  imagevector/images.yaml
Labels: area/audit-logging, kind/enhancement, size/XS, cla: yes, approved, lgtm

#7 Workflow for upgrading image dependencies
  .github/workflows/upgrade-dependencies.yaml
Labels: area/audit-logging, area/dev-productivity, kind/enhancement, size/S, cla: yes, approved, lgtm
